-- Crear tabla de promociones (compatible con estructura BIGINT)
CREATE TABLE IF NOT EXISTS public.promos (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  nombre TEXT NOT NULL,
  descripcion TEXT,
  descuento_porcentaje NUMERIC(5,2) NOT NULL CHECK (descuento_porcentaje >= 0 AND descuento_porcentaje <= 100),
  fecha_inicio TIMESTAMP WITH TIME ZONE NOT NULL,
  fecha_fin TIMESTAMP WITH TIME ZONE NOT NULL,
  activa BOOLEAN DEFAULT true,
  created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW(),
  CONSTRAINT valid_dates CHECK (fecha_fin > fecha_inicio)
);

-- Crear tabla de relación productos-promociones
CREATE TABLE IF NOT EXISTS public.promo_productos (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  promo_id BIGINT NOT NULL REFERENCES public.promos(id) ON DELETE CASCADE,
  producto_id BIGINT NOT NULL REFERENCES public.productos(id) ON DELETE CASCADE,
  created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW(),
  CONSTRAINT promo_productos_unique UNIQUE(promo_id, producto_id)
);

-- Crear índices para mejor rendimiento
CREATE INDEX IF NOT EXISTS promos_fecha_inicio_idx ON public.promos(fecha_inicio);
CREATE INDEX IF NOT EXISTS promos_fecha_fin_idx ON public.promos(fecha_fin);
CREATE INDEX IF NOT EXISTS promos_activa_idx ON public.promos(activa);
CREATE INDEX IF NOT EXISTS promo_productos_promo_id_idx ON public.promo_productos(promo_id);
CREATE INDEX IF NOT EXISTS promo_productos_producto_id_idx ON public.promo_productos(producto_id);

-- Función para actualizar updated_at
CREATE OR REPLACE FUNCTION public.update_promos_updated_at()
RETURNS TRIGGER AS $$
BEGIN
  NEW.updated_at = NOW();
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

-- Trigger para updated_at
DROP TRIGGER IF EXISTS update_promos_timestamp ON public.promos;
CREATE TRIGGER update_promos_timestamp
  BEFORE UPDATE ON public.promos
  FOR EACH ROW
  EXECUTE FUNCTION public.update_promos_updated_at();

-- Habilitar RLS
ALTER TABLE public.promos ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.promo_productos ENABLE ROW LEVEL SECURITY;

-- Eliminar políticas existentes si existen
DROP POLICY IF EXISTS "Permitir acceso completo a promos" ON public.promos;
DROP POLICY IF EXISTS "Permitir acceso completo a promo_productos" ON public.promo_productos;
DROP POLICY IF EXISTS "Promos públicas legibles" ON public.promos;
DROP POLICY IF EXISTS "Admin puede gestionar promos" ON public.promos;
DROP POLICY IF EXISTS "Admin puede gestionar promo_productos" ON public.promo_productos;
DROP POLICY IF EXISTS "Productos de promos públicas legibles" ON public.promo_productos;

-- Crear políticas permisivas (consistente con el resto del sistema)
CREATE POLICY "Permitir acceso completo a promos"
  ON public.promos
  FOR ALL
  USING (true);

CREATE POLICY "Permitir acceso completo a promo_productos"
  ON public.promo_productos
  FOR ALL
  USING (true);

-- Comentarios para documentación
COMMENT ON TABLE public.promos IS 'Tabla de promociones con descuentos por porcentaje';
COMMENT ON TABLE public.promo_productos IS 'Relación muchos-a-muchos entre promociones y productos';
COMMENT ON COLUMN public.promos.descuento_porcentaje IS 'Porcentaje de descuento (0-100)';
COMMENT ON COLUMN public.promos.fecha_inicio IS 'Fecha y hora de inicio de la promoción';
COMMENT ON COLUMN public.promos.fecha_fin IS 'Fecha y hora de fin de la promoción';
COMMENT ON COLUMN public.promos.activa IS 'Indica si la promoción está activa o desactivada manualmente';
